// Module included in the following assemblies:
// install/ossm-installing-openshift-service-mesh.adoc

:_mod-docs-content-type: Concept
[id="ossm-about-discoveryselectors_{context}"]
= About DiscoverySelectors
:context: ossm-about-discoveryselectors

`discoverySelectors` let the mesh administrator control which namespaces the control plane can access. Using a {k8s} label selector, the administrator sets the criteria for the namespaces visible to the control plane, excluding any namespaces that do not match the specified criteria.

[NOTE]
====
Istiod will always open a watch to {ocp-short-name} for all namespaces. However, `discoverySelectors` will ignore objects that are not selected very early in its processing, minimizing costs.
====

[NOTE]
====
`discoverySelectors` is not a security boundary. Istiod will continue to have access to all namespaces even when you have configured your `discoverySelector`.
====

The `discoverySelectors` field accepts an array of {k8s} selectors, which apply to labels on namespaces. You can configure each selector for different use cases, such as:

* Custom label names and values. For example, configure all namespaces with the label `istio-discovery=enabled`.
* A list of namespace labels using set-based selectors with OR logic. For instance, configure namespaces with `istio-discovery=enabled` OR `region=us-east1`.
* Inclusion and exclusion of namespaces. For example, configure namespaces with `istio-discovery=enabled` AND the label `app=helloworld`.

[role="_additional-resources"]
.Additional resources
* link:https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors[Label selectors]
* link:https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements[Resources that support set-based requirements]