// Module included in the following assemblies:
// install/ossm-deploying-multiple-service-meshes-on-single-cluster.adoc

:_mod-docs-content-type: Procedure
[id="ossm-deploying-multiple-control-planes_{context}"]
= Deploying multiple control planes

To configure a cluster to host two control planes, set up separate {istio} resources with unique names in independent {istio} system namespaces. Assign a unique revision name to each {istio} resource to identify the control planes, workloads, or namespaces it manages. Apply these revision names using injection or `istio.io/rev` labels to specify which control plane injects the sidecar proxy into application pods.

Each `{istio}` resource must also configure discovery selectors to specify which namespaces the {istio} control plane observes. Only namespaces with labels that match the configured discovery selectors can join the mesh. Additionally, discovery selectors determine which control plane creates the `istio-ca-root-cert` config map in each namespace, which is used to encrypt traffic between services with mutual TLS within each mesh.

When adding an additional {istio} control plane to a cluster with an existing control plane, ensure that the existing `{istio}` instance has discovery selectors configured to avoid overlapping with the new control plane.

This procedure can be extended to support more than two control planes. The maximum number of service meshes in a single cluster depends on the available cluster resources.

[NOTE]
====
Only one `IstioCNI` resource is shared by all control planes in a cluster, and you must update this resource independent of other cluster resources.
====

.Prerequisites
* The {SMProduct} operator is installed.
* An {istio} CNI resource is created.
+
[NOTE]
====
You can run the following command to check for existing `{istio}` instances:

[source,terminal]
----
$ oc get istios
----
====
* The `istioctl` binary is installed on your localhost.

.Procedure

. Deploy the first control plane by using the following steps:

.. Create the namespace for the first {istio} control plane called `istio-system-1` by running the following command:
+
[source,terminal]
----
$ oc new-project istio-system-1
----

.. Add the following label to the first namespace, which will be used with the Istio `discoverySelectors` field by running the following command:
+
[source,terminal]
----
$ oc label namespace istio-system-1 istio-discovery=mesh-1
----

.. Create a YAML file named `istio-1.yaml` with the name `mesh-1` and the discoverySelector `mesh-1`:
+
.Example configuration
[source,yaml,subs="attributes,verbatim"]
----
kind: Istio
apiVersion: sailoperator.io/v1alpha1
metadata:
  name: mesh-1
spec:
  namespace: istio-system-1
  values:
    meshConfig:
      discoverySelectors:
        - matchLabels:
            istio-discovery: mesh-1
# ...
----

.. Create the first `Istio` resource by running the following command:
+
[source,terminal]
----
$ oc apply -f istio-1.yaml
----

.. To restrict workloads in `mesh-1` from communicating freely with decrypted traffic between meshes, deploy a `PeerAuthentication` resource to enforce mutual TLS (mTLS) traffic within the `mesh-1` data plane. Apply the `PeerAuthentication` resource in the `istio-system-1` namespace by using a configuration file, such as `peer-auth-1.yaml`:
+
[source,terminal]
----
$ oc apply -f peer-auth-1.yaml
----
+
.Example configuration
[source,yaml,subs="attributes,verbatim"]
----
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: "mesh-1-peerauth"
  namespace: "istio-system-1"
spec:
  mtls:
    mode: STRICT
----

. Deploy the second control plane by using the following steps:


.. Create a namespace for the second Istio control plane called `istio-system-2` by running the following command:
+
[source,terminal]
----
$ oc new-project istio-system-2
----

.. Add the following label to the second namespace, which will be used with the Istio `discoverySelectors` field by running the following command:
+
[source,terminal]
----
$ oc label namespace istio-system-2 istio-discovery=mesh-2
----

.. Create a YAML file named `istio-2.yaml`:
+
.Example configuration
[source,yaml,subs="attributes,verbatim"]
----
kind: Istio
apiVersion: sailoperator.io/v1alpha1
metadata:
  name: mesh-2
spec:
  namespace: istio-system-2
  values:
    meshConfig:
      discoverySelectors:
        - matchLabels:
            istio-discovery: mesh-2
# ...
----

.. Create `Istio` resource by running the following command:
+
[source,terminal]
----
$ oc apply -f istio-2.yaml
----

.. Deploy a policy for workloads in the `istio-system-2` namespace to only accept mutual TLS traffic `peer-auth-2.yaml` by running the following command:
+
[source,terminal]
----
$ oc apply -f peer-auth-2.yaml
----
+
.Example configuration
[source,yaml,subs="attributes,verbatim"]
----
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: "mesh-2-peerauth"
  namespace: "istio-system-2"
spec:
  mtls:
    mode: STRICT
----

.Verification

* Verify that both of the {istio} control planes deploy and run. This can be done by validating that the `istiod` pod is successfully running in each {istio} system namespace.
+
.. Verify the `istio-system-1` configuration by running the following command:
+
[source,terminal]
----
$ oc get pods -n istio-system-1
----
+
You should see output similar to the following example:
+
.Example output
[source,terminal]
----
NAME                            READY   STATUS    RESTARTS   AGE
istiod-mesh-1-b69646b6f-kxrwk   1/1     Running   0          4m14s
----
+
.. Verify the `istio-system-2` configuration by running the following command:
+
[source,terminal]
----
$ oc get pods -n istio-system-2
----
+
You should see output similar to the following example:
+
.Example output
[source,terminal]
----
NAME                            READY   STATUS    RESTARTS   AGE
istiod-mesh-2-8666fdfc6-mqp45   1/1     Running   0          118s
----