// Module included in the following assemblies:
// install/ossm-deploying-multiple-service-meshes-on-single-cluster.adoc

:_mod-docs-content-type: PROCEDURE
[id="ossm-deploying-multiple-control-planes_{context}"]
= Deploying multiple control planes

This procedure can be extended to support more than two control planes. The maximum number of service meshes in a single cluster depends on the available cluster resources.

.Prerequisites
* The {SMProduct} operator is installed.
* An {istio} CNI resource is created.
+
[NOTE]
====
You can run the following command to check for existing `{istio}` instances:

[source,terminal]
----
$ oc get istios
----
====
* The `istioctl` binary is installed on your localhost.

[id="ossm-deploying-first-control-plane_{context}"]
== Deploying the first control plane

Deploy the first control plane by using the following steps:

.Procedure

. Create the namespace for the first {istio} control plane called `istio-system-1` by running the following command:
+
[source,terminal]
----
$ oc new-project istio-system-1
----

. Add the following label to the first namespace, which is used with the {istio} `discoverySelectors` field by running the following command:
+
[source,terminal]
----
$ oc label namespace istio-system-1 istio-discovery=mesh-1
----

. Create a YAML file named `istio-1.yaml` with the name `mesh-1` and the discoverySelector `mesh-1`:
+
.Example configuration
[source,yaml,subs="attributes,verbatim"]
----
kind: Istio
apiVersion: sailoperator.io/v1alpha1
metadata:
  name: mesh-1
spec:
  namespace: istio-system-1
  values:
    meshConfig:
      discoverySelectors:
        - matchLabels:
            istio-discovery: mesh-1
# ...
----

. Create the first `{istio}` resource by running the following command:
+
[source,terminal]
----
$ oc apply -f istio-1.yaml
----

. To restrict workloads in `mesh-1` from communicating freely with decrypted traffic between meshes, deploy a `PeerAuthentication` resource to enforce mutual TLS (mTLS) traffic within the `mesh-1` data plane. Apply the `PeerAuthentication` resource in the `istio-system-1` namespace by using a configuration file, such as `peer-auth-1.yaml`:
+
[source,terminal]
----
$ oc apply -f peer-auth-1.yaml
----
+
.Example configuration
[source,yaml,subs="attributes,verbatim"]
----
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: "mesh-1-peerauth"
  namespace: "istio-system-1"
spec:
  mtls:
    mode: STRICT
----

[id="ossm-deploying-second-control-plane_{context}"]
== Deploying the second control plane

Deploy the second control plane by using the following steps:

.Procedure

. Create a namespace for the second {istio} control plane called `istio-system-2` by running the following command:
+
[source,terminal]
----
$ oc new-project istio-system-2
----

. Add the following label to the second namespace, which is used with the {istio} `discoverySelectors` field by running the following command:
+
[source,terminal]
----
$ oc label namespace istio-system-2 istio-discovery=mesh-2
----

. Create a YAML file named `istio-2.yaml`:
+
.Example configuration
[source,yaml,subs="attributes,verbatim"]
----
kind: Istio
apiVersion: sailoperator.io/v1alpha1
metadata:
  name: mesh-2
spec:
  namespace: istio-system-2
  values:
    meshConfig:
      discoverySelectors:
        - matchLabels:
            istio-discovery: mesh-2
# ...
----

. Create the second `{istio}` resource by running the following command:
+
[source,terminal]
----
$ oc apply -f istio-2.yaml
----

. Deploy a policy for workloads in the `istio-system-2` namespace to only accept mutual TLS traffic `peer-auth-2.yaml` by running the following command:
+
[source,terminal]
----
$ oc apply -f peer-auth-2.yaml
----
+
.Example configuration
[source,yaml,subs="attributes,verbatim"]
----
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: "mesh-2-peerauth"
  namespace: "istio-system-2"
spec:
  mtls:
    mode: STRICT
----

[id="ossm-verifying-multiple-control-planes_{context}"]
== Verifying multiple control planes

Verify that both of the {istio} control planes deploy and run. This can be done by validating that the `istiod` pod is successfully running in each {istio} system namespace.

. Verify the `istio-system-1` configuration by running the following command:
+
[source,terminal]
----
$ oc get pods -n istio-system-1
----
+
You should see output similar to the following example:
+
.Example output
[source,terminal]
----
NAME                            READY   STATUS    RESTARTS   AGE
istiod-mesh-1-b69646b6f-kxrwk   1/1     Running   0          4m14s
----

. Verify the `istio-system-2` configuration by running the following command:
+
[source,terminal]
----
$ oc get pods -n istio-system-2
----
+
You should see output similar to the following example:
+
.Example output
[source,terminal]
----
NAME                            READY   STATUS    RESTARTS   AGE
istiod-mesh-2-8666fdfc6-mqp45   1/1     Running   0          118s
----