// Module included in the following assemblies:
//
// * service-mesh-docs-main/metrics/ossm-metrics.adoc

:_mod-docs-content-type: PROCEDURE
[id="ossm-config-openshift-monitoring-ambient-mode_{context}"]
= Configuring OpenShift Monitoring with Service Mesh ambient mode

[role="_abstract"]
You can integrate {SMProductName} with user-workload monitoring to enable observability in your service mesh ambient mode. User-workload monitoring provides access to essential built-in tools and is required to run Kiali, the dedicated console for {istio}. 

.Prerequisites

* You have installed the {SMProductName} Operator.

* You have enabled the user-workload monitoring.
+
[NOTE]
====
You can enable user-workload monitoring by applying the `ConfigMap` change for metrics integration. For more information, see link:https://docs.openshift.com/container-platform/latest/observability/monitoring/enabling-monitoring-for-user-defined-projects.html[Enabling monitoring for user-defined projects].
====

* You have deployed the Bookinfo application in ambient mode to use the following example. For more information, see "Deploying the Bookinfo application in {istio} ambient mode".

.Procedure

. Create a YAML file named `service.yml.yml` to define a `ServiceMonitor` resource that uses the metrics exposed by the ztunnel, similar to the following example:

+
[source,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: ztunnel
  namespace: ztunnel
  labels:
    app: ztunnel
    service: ztunnel
spec:
  selector:
    app: ztunnel
  ports:
    - name: http-monitoring
      protocol: TCP
      port: 15020
      targetPort: 15020
----

. Apply the YAML file by running the following command:
+
[source,terminal]
----
$ oc apply -f service.yml
----

. Create a YAML file named `servicemonitor.yml` to define a `ServiceMonitor` resource that monitors the {istio} control plane, similar to the following example:
+
[source,yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod-monitor
  namespace: istio-system
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      istio: pilot
  endpoints:
  - port: http-monitoring
    interval: 30s
----

. Apply the YAML file by running the following command:
+
[source,terminal]
----
$ oc apply -f servicemonitor.yml
----

. Create a YAML file named `servicemonitorztunnel.yml` to define a `ServiceMonitor` resource that collects the ztunnel metrics, similar to the following example:
+
[source,yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ztunnel-monitor
  namespace: ztunnel
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      service: ztunnel
  endpoints:
  - port: http-monitoring
    interval: 30s
----

. Apply the YAML file by running the following command:
+
[source,terminal]
----
$ oc apply -f servicemonitorztunnel.yml
----

. Optional: Deploy a waypoint proxy to enable optional Layer 7 (L7) features, such as HTTP metrics and traces in ambient mode:

.. Deploy a waypoint proxy. For more information, see "Deploying a waypoint proxy".

.. Create a YAML file named `servicemonitorwaypoint.yml` to define a `ServiceMonitor` resource that collects the waypoint proxy metrics, similar to the following example:
+
[source,yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: waypoint-monitor
  namespace: bookinfo
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      service: waypoint
  endpoints:
  - port: http-monitoring
    interval: 30s
----

. Apply the YAML file by running the following command:
+
[source,terminal]
----
$ oc apply -f servicemonitorwaypoint.yml
----
+
[NOTE]
====
A waypoint proxy generates Layer 4 (L4) and L7 metrics. It scopes these statistics by Envoy proxy functions, including upstream connections, listeners, the HTTP connection manager, TCP proxy, and router.
====