:_mod-docs-content-type: Procedure
[id="ossm-accessing-bookinfo-application-using-gateway-api"]
= Accessing the Bookinfo application by using Gateway API
:context: ossm-accessing-bookinfo-application-using-gateway-API

The {k8s} Gateway API deploys a gateway by creating a `Gateway` resource. In {ocp-product-title} 4.15 and later, the Gateway API custom resource definitions (CRDs) are available but disabled by default. To use them, you must manually enable the CRDs. In versions 4.18 and earlier, you must manually install the CRDs. Starting with {ocp-product-title} 4.19, the platform automatically installs and manages these CRDs, and you can no longer create, update, or delete them.

If the current subscription is in conflict during an upgrade, the Gateway API for Ingress cannot be used. You must resolve the subscription conflict manually before continuing with the configuration.

[NOTE]
====
Red{nbsp}Hat provides support for using the {k8s} Gateway API with {SMProductName}. Red{nbsp}Hat does not provide support for the {k8s} Gateway API custom resource definitions (CRDs). In this procedure, the use of community Gateway API CRDs is shown for demonstration purposes only.
====

.Prerequisites

* You are logged in to the {ocp-product-title} web console as `cluster-admin`.

* The {SMProductName} Operator must be installed.

* The {istio} resource must be deployed.

.Procedure

. Enable the Gateway API CRDs for {ocp-product-title} 4.18 and earlier, by running the following command:
+
[source,terminal]
----
$ oc get crd gateways.gateway.networking.k8s.io &> /dev/null ||  { oc kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.0.0" | oc apply -f -; }
----

. Create and configure a gateway using a `Gateway` resource and `HTTPRoute` resource:
+
[source,terminal]
----
$ oc apply -f https://raw.githubusercontent.com/openshift-service-mesh/istio/release-1.24/samples/bookinfo/gateway-api/bookinfo-gateway.yaml -n bookinfo
----
+
[NOTE]
====
To configure a gateway with the `bookinfo` application by using the Gateway API, this example uses a sample gateway configuration file that must be applied in the namespace where the application is installed.
====

. Ensure that the Gateway API service is ready, and has an address allocated:
+
[source,terminal]
----
$ oc wait --for=condition=programmed gtw bookinfo-gateway -n bookinfo
----

. Retrieve the host, port and gateway URL:
+
[source,terminal]
----
$ export INGRESS_HOST=$(oc get gtw bookinfo-gateway -n bookinfo -o jsonpath='{.status.addresses[0].value}')
$ export INGRESS_PORT=$(oc get gtw bookinfo-gateway -n bookinfo -o jsonpath='{.spec.listeners[?(@.name=="http")].port}')
$ export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT
----

. Obtain the gateway host name and the URL of the product page:
+
[source,terminal]
----
$ echo "http://${GATEWAY_URL}/productpage"
----

. Verify that the `productpage` is accessible from a web browser.